### ISSUE TITLE
intallation

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [ryjm/srrs#11]
can you provide more clear instructions how can I get this app on my landscape? 
shouldn't it instead of `npm serve` be `npm run serve` ?

I couldn't get it to work myself

**Comment by ryjm** [comment]
yes sorry! i'll do a from scratch installation and make sure everything works. 

i neglected to mention that you need to mount your planet's pier to unix, and then change your .urbitrc to point to that directory. then a `|commit %home` to get urbit to see them, and a `|start %srrs` to actually run the app.

**Comment by ryjm** [comment]
sounds a bit complicated, but you have to remember urbit is like a VM - it has its own filesystem, http server, all that jazz. using npm to get your files in is just how we're doing it in lieue of a package manager, but you can also just copy in all the app files directly into your pier (after mounting of course) and it should work the same.

**Comment by ryjm** [comment]
i've updated the installation instructions, let me know if you can get it running!

**Comment by gilletteonmeheleparim** [comment]
I couldn't get it running.
getting this response after running :launch &launch-action [%add %srrs [[%basic 'srrs' '/~srrs/srrs.png' '/~srrs'] %.y]]
```
/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 3].[9 5]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 33].[7 37]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 23].[7 37]>

ford: %call execution failed:

\/ford: %cast failed to call +grab arm in /~nortex-ramnyd/home/0/mar/launch/a\/

ction/hoon:

\/ \/

ford: %cast failed while trying to cast from noun to launch-action:

ford: failed to %cast
```

**Comment by ryjm** [comment]
oops, i need to update the readme - new path is ‘/~srrs-files/srrs.png’. 

the new tile process / file server stuff is going through some growing pains. hopefully they get fixed soon and you don’t have to run this. 
GitHub <notifications@github.com> wrote:
“I couldn't get it running.
 getting this response after running :launch &launch-action [%add %srrs [[%basic 'srrs' '/~srrs/srrs.png' '/~srrs'] %.y]]

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 3].[9 5]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 33].[7 37]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 23].[7 37]>

ford: %call execution failed:

\/ford: %cast failed to call +grab arm in /~nortex-ramnyd/home/0/mar/launch/a\/

ction/hoon:

\/ \/

ford: %cast failed while trying to cast from noun to launch-action:

ford: failed to %cast”

**Comment by gilletteonmeheleparim** [comment]
getting exactly the same error with ‘/~srrs-files/srrs.png’ path

**Comment by ryjm** [comment]
hm, can you confirm that you have the latest bash hash? what's the output of `+trouble`?

**Comment by ryjm** [comment]
i'm guessing you're on an older version, since even if you put in the wrong path this should still result in a new tile in landscape (albiet with a missing picture).

**Comment by gilletteonmeheleparim** [comment]
[ [%base-hash 0vs.9288r.bdja5.ic2br.jigbg.0kduq.stbiu.npcsj.mtsk0.dhf80.l4gq1]

I do get the empty tile slot but no actual tile

**Comment by ryjm** [comment]
ah yeah, you're on an old version. 

you could try syncing from ~middev? |merge %home ~middev %kids

**Comment by gilletteonmeheleparim** [comment]
it's doing nothing

**Comment by ryjm** [comment]
hm, looks like you broke my star! i guess we still can't merge like this... i think it's because of https://github.com/urbit/urbit/pull/3099

**Comment by ryjm** [comment]
anyway, you might want to check with your sponsor and see why you aren't getting any updates.

**Comment by gilletteonmeheleparim** [comment]
oops im sorry didn't mean to :D

I did get some update last week or sometime but I had to manually toggle it, can't remember the exact commands to do it now

**Comment by ryjm** [comment]
I believe it's `|ota` now - if that runs, you know you're on the latest Ford Fusion build (which I think you're not, considering that `:launch` didn't work properly). Otherwise, it's the `|merge` command (or `|sync`, but that just runs a merge) I gave above, except with your sponsor instead of ~middev. 

Feel free to reach out to me on the urbit discord (or urbit itself, I'm ~littel-wolfur) if you need help.
GitHub <notifications@github.com> wrote:
“oops im sorry didn't mean to :D

I did get some update last week or sometime but I had to manually toggle it, can't remember the exact commands to do it now”

**Comment by gilletteonmeheleparim** [comment]
I've written you on urbit

**Comment by ryjm** [comment]
closing, `|merge %home ~middev %kids` works now.
