### ISSUE TITLE
`init-cards` shouldn't be sent unconditionally

### ISSUE THREAD

**Issue by philipcmonk** [ryjm/srrs#20]
It looks like %file-server crashes if you rebind an already-bound path.  Seems like `init-cards` should be sent only once, not on every load.

Additionally, urbit/urbit#3379 changed the `%serve-dir` request slightly.  You should be able to just add `%.n` at end of each call.

**Comment by ryjm** [comment]
fixed by https://github.com/ryjm/srrs/commit/21942d7ca2c85604f93c62607195f1b3bf884160
